### ISSUE TITLE
Dev environment na Windows-ih

### ISSUE THREAD

**Issue by jernej-m** [aokranj/website-aokranj.com#94]
Dokument za referenco: https://github.com/aokranj/website-aokranj.com/blob/master/doc/docker-dev-environment.md

## Okolje:
- Windows 11 Pro
- WSL 2 Ubuntu 22.04.1 LTS
- Docker Desktop

### Step 3: 
"wp-config.php.SAMPLE" se sedaj imenuje "wp-config-local.php.SAMPLE". WP-CLI pa tudi (zgleda, da zaradi novejše verzije) zahteva da se wp-config datoteka imenuje "wp-config-local.php"

### Step 4: 
Ko zaženem `./sbin/docker-compose-up` mi javi error: `service "phpmyadmin" depends on undefined service aokranj-mariadb: invalid compose project`. V `docker/docker-compose.yaml` sem moral popraviti:
```
depends_on:
      - aokranj-mariadb
```
v
```
depends_on:
      - mariadb
```
Izgleda da v depends_on ne moraš vpisati ime container-ja, ampak mora biti ime service-a.

### Step 7:
Komanda `./sbin/deploy-here` se zažene lokalno. Sveža inštalacija Ubuntu-ja pa ne prinese php-ja, wordpress-a in ostalih paketov, ki jih zahteva ta skripta. Rešil sem tako, da sem jih zagnal v "aokranj-webserver" container-ju. @bostjan je predlagal:

![deploy-here](https://user-images.githubusercontent.com/58071520/194114730-20847b9a-b9b3-481e-8c01-8ad6bbc76053.png)

## ToDo
Predlagam:
- [ ] Naredi se navodila za postavitev Docker Desktop, WSL2, Ubuntu na Windowsih
- [ ] Step 3: Popravi se `doc/docker-dev-environment.md`
- [ ] Step 4: Popravi se `docker/docker-compose.yaml`???
- [ ] Step 7: Doda se `sbin/deploy-in-docker`

**Comment by bostjan** [comment]
### `depends_on: aokranj-mariadb` vs `depends_on: mariadb`:
Izgleda, da je tole specifično v posameznem okolju. Meni na OS X (+ Docker desktop) delata BP obe varianti, zato nikol nisem opazil, da je kaj narobe. Kar fixni, da bo delalo povsod.

**Comment by jernej-m** [comment]
Glede točke 7.

Če bi naredili `sbin/deploy-in-docker` podobno kot `sbin/wp-in-docker`, je mal smotano, ker je v `sbin/deploy-here` precej enih `wp` komand. Vsem tem `wp` komandam bi bilo treba potem dodati `--allow-root`. Tako, da v temo primeru bi bilo treba skripto klicati z `docker exec -i aokranj-webserver ./deploy-in-docker` in ne samo z zagonom enega file-a.

Sem pa še malo razmišljal pa iskal druge alternative in sem našel, da so dodali `WP_CLI_ALLOW_ROOT` environment variablo (https://make.wordpress.org/cli/2021/05/19/wp-cli-v2-5-0-release-notes/). V tem primeru bi lahko `--allow-root` dali ven tudi iz drugih skript. Ne vem pa kolk je to varno za v produkcijo. Če laufa v dockerju potem je safe, i guess? :)

**Comment by bostjan** [comment]
Oh, `WP_CLI_ALLOW_ROOT` - dobr si tole nasel. Ko sem nazadnje gledal za to opcijo, [se ni bila podprta](https://make.wordpress.org/cli/2021/05/19/wp-cli-v2-5-0-release-notes/), zato je `--allow-root` v teh skriptah.

Drugace pa upam, da sva se razumela:
- `sbin/deploy-in-docker` naj bo samo _convenience wrapper_, ki uporabi `docker exec -i aokranj-webserver ./sbin/deploy-here`, da pozene `sbin/deploy-here` v samem kontejnerju.
- Tako skripto je (vsaj meni) fajn imeti pri roki, da mi ni treba ugotavljati, kaksen tocno `docker exec...` ukaz ze moram pognati, da bo pravi. Alternativa je imeti `docker exec...` ukaz v dokumentaciji, samo potem moras _vedno_ copy-pastat, al pa ful vec napisat v konzolo. Ce mas pa convenience wrapper pripravljen, pa par črk in par tab-ov klofnes in zaziher & hitro poganjaš pravi ukaz.

Razlog, zakaj tole^ pisem, je tale tvoj zapis: `docker exec -i aokranj-webserver ./deploy-in-docker`. V temu ukazu bi pricakoval `deploy-here` in ne `deploy-in-docker`.

BTW imas dve opciji, kako postavt ta env variable:
1. Lahko skozi `docker exec` notri potisnes, [takole](https://stackoverflow.com/questions/27812548/how-to-set-an-environment-variable-in-a-running-docker-container).
2. Lahko pa samo `sbin/deploy-here` predelas tako, da dodas detekcijo docker environmenta, takole:
```bash
#!/bin/bash

if [ -f /.dockerenv ]; then
    if [[ $(id -u) -eq 0 ]]; then
        export WP_CLI_ALLOW_ROOT="true"
    fi
fi

# ...
```

### Docker vs. root

Iskreno se z varnostjo tule nismo nič igrali, ker v kontejnerju itak laufa PHP znotraj  Apache-a, zato vsi produkcijski requesti, ki letijo v kontejner, tecejo kot `www-data` user. Za tele management posege od zunaj je bilo pa do sedaj vseeno, tudi ce jih kar z rootom naredimo. Ker ce jih delas kot ne-root, imas lahko tezavo, ce lastnik datotek ni isti UID kot user, ki ga uporabi `docker exec...` znotraj kontejnerja (zato, ker ta `sbin/deploy-here` skripta postavlja pravice direktorijev).

Zdej, realno stvar lahko dodamo v Dockerfile novega userja in laufamo vse te `docker exec` ukaze kot ta non-root user. Ker sicer se zdi, da je glavni namen te kode, da zrihta pravice, pa je to le pol slike - drugi del je ta, da nas **opozori**, ce pravice niso pravilne in ce jih ne more pofixat.

Tako da, zaenkrat je bilo tole poganjanje z root-om bolj stvar udobja - ce pozenes kot root, so lahko PHP diri/fajli od kateregakoli userja in jih bo skripta pravilno `chmod`-ala. :)

**Comment by bostjan** [comment]
>  V tem primeru bi lahko --allow-root dali ven tudi iz drugih skript.

Be my guest, seveda! :)

**Comment by andrazjelenc** [comment]
V tem [referenčnem dokumentu](https://github.com/aokranj/website-aokranj.com/blob/master/doc/docker-dev-environment.md) je za popravit že prvi step. Pri `git clone git@github.com:aokranj/website-aokranj.com
` manjka .git na koncu URLja

**Comment by bostjan** [comment]
@andrazjelenc, `.git` suffix ni potreben pri temu ukazu, vsaj na mojih sistemih (OS X, Linux) ne - a je slucajno nujen na Windows-ih?

**Comment by andrazjelenc** [comment]
Imaš prav ja, tudi na Windowsih dela brez. Sem imel težave drugje, sem uredil.

Sem pa odkril še eno zadevo. Na https://stg.aokranj.com/ link Moj AO še vedno kaže na produkcijo in me pelje na https://www.aokranj.com/wp-login.php čeprav bi me moral peljati na https://stg.aokranj.com/wp-login.php

Isti problem se nato iz staginga podeduje na dev postavitev. 
Eazy rešitev je, da se Moj AO link popravi na relativni URL /wp-login.php potem je okej.

![image](https://user-images.githubusercontent.com/10503118/194762352-7bccafdd-5e1d-424e-8a7d-e2261ea90ca0.png)

**Comment by bostjan** [comment]
@andrazjelenc, tale login link je samo najbolj očitna manifestacija globljega problema - v bazi so napačni URL-ji. 

Predvidevam, da po prenosu s produkcije [tale ukaz](https://github.com/aokranj/website-aokranj.com/blob/master/doc/runbook/database-transfers.md?plain=1#L70) ni bil pognan:
```
./sbin/wp search-replace 'https://www.aokranj.com' 'https://stg.aokranj.com'
```

Sem sedaj pognal, je fixed. Zelo verjetno je, da sem kar jaz pozabil na tole.

**Comment by bostjan** [comment]
@jernej-m, a je PR #95 razrešil vse navedene probleme? Če da, lahko tole zapremo.

> Naredi se navodila za postavitev Docker Desktop, WSL2, Ubuntu na Windowsih

A je tole dejansko treba dokumentirat? A je potrebno postorit karkoli dodatnega poleg instalacije nadevenega software-a? 

Kakorkoli, če se ti zdi smotrno, da dokumentiramo bolj ko samo z linkom na kak zunanji site, kjer so ze ta navodila, potem je najbolje da se v [dev env dokumentaciji](https://github.com/aokranj/website-aokranj.com/blob/master/doc/docker-dev-environment.md) v tekstu `Docker Desktop running on your workstation (or Linux workstation with Docker installed)` naredi link na nov dokument, kjer je opisan postopek instalacije za posamezno okolje. Lahko je zaenkrat opisano samo za Windows-e, navodila za ostala okolja lahko dodamo kasneje po potrebi.

**Comment by bostjan** [comment]
> Mojih 5 centov: development na windows ... ne.

@HriBB, lej, ne mormo glih diktirat, da naj si ljudje kupijo Mac-e :)

Če se potrebuje, in če so osebe, ki tako dev okolje potrebujejo, pripravljene PR-jat spremembe, ki so potrebne v naši kodi, da bo podprto tudi Windows okolje, zakaj pa ne.

PS: Da ne bo pomote - moje osebno mnenje je zelo podobno tvojemu. Povedano z drugimi besedami - osebno sem mnogo bolj efektiven na Mac-u ali Linux-u kot pa na Windows-ih.

**Comment by HriBB** [comment]
Glavno da je UNIX :P @andrazjelenc sam mal se hecam ;) ti je ratalo zrihtat dev okolje na windows?

**Comment by andrazjelenc** [comment]
Jups, vse ok.

**Comment by andrazjelenc** [comment]
Navodil za postavljanje Dockerja na Windowsih po mojem tukaj ne rabimo.
